version: '3.1'

services:

  db:
    image:  postgres:16
    container_name: acc_db
    ports:
      - 32701:5432
    volumes:
      - data:/var/lib/postgresql/data
    # command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accc
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5

  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: acc_rabbitmq
    hostname: localhost
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: unless-stopped

volumes:
  data: